### ISSUE TITLE
How to deal with nextera extension in PCR1

### ISSUE THREAD

**Issue by LZarri** [ssb22/PrimerPooler#1]
Hello, and thanks for this power software! How should I input my fasta file if my primers in PCR1 (amplification) have illumina sequencing adapters on them? After reading through the readme, it seems that the "tailed" option is for PCR2, when individual-specific barcodes are annealed to either end of the amplified fragment. I am currently just including the illumina adapters on either end of my PCR1 primers, as this is how I am ordering them from IDT.
Best,
Liam

**Comment by ssb22** [comment]
Hi Liam, Wendy and I are not sure what you mean by PCR1 vs PCR2, but the `>tagF` and `>tagR` options apply the given tag to all primers by default. I.e. if you just specify a `>tagF` and a `>tagR` once at the top of the file, it will apply the tagF to *all* the forward primers and the tagR to *all* the reverse primers.  If instead you want to tag individual primers you'd need to set extra tags.  Perhaps I was trying to explain too many different options in the same paragraph of the readme.

**Comment by LZarri** [comment]
Thanks so much for the clarification! So if I understand correctly, any
sequence that comes with all primers, for example illumina adapters that
are attached to the sequence-specific primers, we can include these as
>tagF and >tagR, instead of on each primer individually? I mistakenly thought that the tagF and tagR were sequences that got attached to the primers in another round of PCR.
Thanks,
Liam

**Comment by ssb22** [comment]
Hi Liam, yes that's right.
